#!/bin/sh
#usage: "vlan Number" "VM network interface"

. /etc/pvm.conf 

if [[ -z $1 || -z $2 ]]; then
	echo "usage: ifup-vlan# vlan# vmnet-tap"
	exit 1;
fi

switch="brv$1"

# Bring up the tap interface, passed in by kvm as $1
$ifconfig $2 0.0.0.0 up

# Add the tap interface to the bridge
$brctl addif ${switch} ${2} || exit 1

# Ensure a defined exit code.
exit 0
