#!/bin/bash
# Copyright PDNSoft Co.
# by: hamid jafarian

# Makes Vlans ifup scripts 
# Thay may used in "qemu" command for net interfaces

. /etc/pvm.conf 

for i in $( read_config_file "$basedir/etc/vlans" ); do
	$sed -e "s/NNN/$i/" "$basedir/Scripts/ifup-vlanNNN" > "$basedir/Scripts/ifup-vlan$i";
	chmod +x "$basedir/Scripts/ifup-vlan$i";
done
