#!/bin/bash
# Copyright PDNSoft Co.
# By: HMT
# Creates Vlan Ethernets and their associated bridges

. /etc/pvm.conf

# Trunk Ethernet
teth=$( read_config_file "$basedir/etc/trunk-eth" )

$ifconfig $teth 0.0.0.0 up

$modprobe "8021q" 

for i in `$sed -e "/^#/d" "$basedir/etc/vlans" `; do
	$vconfig add $teth $i
	$ifconfig $teth.$i 0.0.0.0 up

	$brctl addbr brv$i
	if [[ "$?" -eq "0" ]]; then
		$ifconfig brv$i 0.0.0.0 up
	fi

	$brctl addif brv$i $teth.$i
	$brctl stp brv$i on
done




