#!/bin/sh

# The original line used by kvm to find the bridge.  Assumes only a single NIC.
#switch=$(ip route ls | awk '/^default / { for(i=0;i<NF;i++) { if ($(i) == "dev") print $(i+1) }}')

# Lock in the bridge interface to use, as configured via /etc/network/interfaces
switch="br0"

# Bring up the tap interface, passed in by kvm as $1
/sbin/ifconfig ${1} 0.0.0.0 up

# Add the tap interface to the bridge
/usr/sbin/brctl addif ${switch} ${1} || exit 1

# Ensure a defined exit code.
exit 0
