#!/bin/bash
#  This Script Makes Snapshots from "VM"s that are running on the local host.
#  He also rotates Snaps: Remove the Oldest Snap, If Number of 
#+ Snapshots be Greater then then defined maximum.

. /etc/pvm.conf

max_snaps="2"

vms=$( $pvmctl "status" | $sed -e "1d" )
exclude_vms=( $( read_config_file "$cf_snap_exclude" ) )

for i in $vms; do
	search_array "$i" "${exclude_vms[@]}"
	if [[ $? -eq 0 ]]; then
		echo "Process \"$i\" ..."
		rotate_snaps "$i" $max_snaps
		$pvmctl "mksnap" "$i" "$autosnaps_tag$RANDOM"
	fi
done

