#!/bin/bash
# PDNCo. Virtualization System
# This file creates initial directories

BASEDIR="/PDNCo."

mkdir "$BASEDIR/VMStorage"
mkdir -p "$BASEDIR/VMStorage/etc/kvm"
mkdir -p "$BASEDIR/VMStorage/var/run/kvm"
mkdir "$BASEDIR/Scripts"
